"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[input.prepend_keymap]]
on = "<Esc>"
run = "close"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"
