[mgr]
show_hidden = true
show_symlink = true

[[opener.edit]]
run = 'micro %s'
desc = "micro"
block = true
for = "unix"

[[opener.edit]]
run = 'code %s'
desc = "Visual Studio Code"
block = false

[[opener.edit]]
run = '${EDITOR:-micro} %s'
desc = "$EDITOR"
block = true
for = "unix"

[[plugin.prepend_fetchers]]
group = "git"
url   = "*"
run  = "git"

[[plugin.prepend_fetchers]]
group = "git"
url   = "*/"
run  = "git"
